# Generated by Django 4.2.13 on 2024-09-15 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='imagemanga',
            field=models.ImageField(upload_to='imagemangachapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='namemanga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagechapter', to='api.manga'),
        ),
    ]
