# Generated by Django 4.2.13 on 2024-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chapter_imagemanga_alter_chapter_namemanga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='imagemanga',
            field=models.ImageField(blank=True, null=True, upload_to='imagemangachapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='numberchapter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manga',
            name='reviews',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
